# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0109c6660f6a7f021e57147fba8b2781a6c7814a6d3a49fcc49dd92c5a684c97690b08529d3f430f3751725a79ed662aeea891d4beaa82319ebc673ee3ea84a5

test:
  secret_key_base: e56de1a1ccd82d3a41e6d7fcfad297c956f90380dc9dc8a9a639b8b7e26302021cd75f0bd5c8defc436efdfcc65f2995f0b88452a65f72d6b4605ec9832c7e90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
